; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_TYPE_ITEM
	const MARTTYPE_TM

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_CHERRYGROVE
	const MART_CHERRYGROVE_DEX
	const MART_VIOLET1
	const MART_VIOLET2
	const MART_AZALEA1
	const MART_AZALEA2
	const MART_CIANWOOD
	const MART_GOLDENROD_2F_1
	const MART_GOLDENROD_2F_2
	const MART_GOLDENROD_3F
	const MART_GOLDENROD_4F
	const MART_GOLDENROD_5F_1	
	const MART_GOLDENROD_5F_2
	const MART_OLIVINE1
	const MART_OLIVINE2
	const MART_ECRUTEAK1
	const MART_ECRUTEAK2
	const MART_MAHOGANY_1
	const MART_MAHOGANY_2
	const MART_BLACKTHORN_1
	const MART_BLACKTHORN_2
	const MART_VIRIDIAN
	const MART_PEWTER1
	const MART_PEWTER2
	const MART_CERULEAN1
	const MART_CERULEAN2
	const MART_LAVENDER
	const MART_VERMILION
	const MART_CELADON_2F_1
	const MART_CELADON_2F_2
	const MART_CELADON_2F_3
	const MART_CELADON_3F
	const MART_CELADON_4F
	const MART_CELADON_5F_1
	const MART_CELADON_5F_2
	const MART_FUCHSIA
	const MART_SAFFRON1
	const MART_SAFFRON2
	const MART_MT_MOON
	const MART_INDIGO_PLATEAU
	const MART_UNDERGROUND
	const MART_UNDERGROUND2
	const MART_UNDERGROUND3
	const MART_UNDERGROUND4
	const MART_UNDERGROUND5
DEF NUM_MARTS EQU const_value
